#!/bin/sh

#TODO: look in .cvsignore

if [ "$1" ]
then CURDIR=$1
else CURDIR=.
fi

if [ -e CVS/Entries ]
then for X in *
     do  if test -e .cvsignore && \
            (ls -d `cat .cvsignore` 2> /dev/null | grep -q "^$X\$")
         then echo '[34m'ignoring $CURDIR/$X'[0m'
         else test -f "$X" && (grep -q "^/$X/" CVS/Entries || echo $CURDIR/$X)
              if [ -d "$X" -a "$X" != "CVS" ]
              then (cd $X && $0 $CURDIR/$X)
              fi
         fi
     done
else echo '[33m'Not found: $CURDIR/CVS/Entries'[0m/'
     exit 1
fi

#cvs -q update -d $* | \
#  sed -e 's/^? .*$/[35m&[0m/' \
#      -e 's/^C .*$/[33m&[0m/' \
#      -e 's/^M .*$/[36m&[0m/' \
#      -e 's/^[PU] .*$/[34m&[0m/'

