#!/usr/bin/python
import sys
from datetime import datetime

# TODO: try other formats
fmt = '%Y-%m-%d %H:%M:%S'

d1 = datetime.strptime(sys.argv[1], fmt)
d2 = datetime.strptime(sys.argv[2], fmt)

if d1 < d2:
    delta = d2 - d1
    print 'd2-d1:'
else:
    delta = d1 - d2
    print 'd1-d2:'
print str(delta)
if delta.days:
    print '(%.2f days)' % (float(delta.days) + float(delta.seconds) / 86400.0)
else:
    if delta.seconds >= 3600:
        print '(%.2f hours)' % (float(delta.seconds) / 3600.0)
    elif delta.seconds >= 60:
        print '(%.2f minutes)' % (float(delta.seconds) / 60.0)
