#!/bin/sh

if [ -z "$*" ]
then echo Argument needed
     exit 1
fi

/usr/bin/find . \( \( -name .svn -o -name .git \) -prune -fprint /dev/null \) \
   -or \( -regex '.*SCons.*' -print0 \) \
 | xargs -0 fgrep "$@" /dev/null \
 | sed -e 's/^[^:]*:/[35m&[0m/'

