#!/bin/sh

SUFFIX="$1"
shift

if [ -z "$*" ]
then echo "Usage: fgrepext suffix <fgrep arguments>"
     exit 1
fi

/usr/bin/find . \( \( -name .svn -o -name .git \) -prune -fprint /dev/null \) \
   -or \( -name "*.${SUFFIX}" -print0 \) \
 | xargs -0 fgrep "$@" /dev/null \
 | sed -e 's/^[^:]*:/[35m&[0m/'

