#!/bin/sh

# NOTE:
#  fgrepsr[c] -- uses xargs, much faster on Windows, but may hit
#                cmdline limit?
#  fgrepsrr[c] -- uses find -exec, much slower on Windows.

if [ -z "$*" ]
then echo Argument needed
     exit 1
fi

/usr/bin/find . \( \( -name .svn -o -name .git \) -prune -fprint /dev/null \) \
   -or \( -regex '.*\.[hH]\([hH]\|[pPxX][pPxX]\)?' -print0 \) \
 | xargs -0 fgrep "$@" /dev/null \
 | sed -e 's/^[^:]*:/[35m&[0m/'

