#!/bin/sh
#
# Print the sizes (in blocks) of files recursively, but prune .svn directory.

set -ex
/usr/bin/find . \( \( -name .svn -o -name .git \) -prune \) \
            -or \( -type f -print0 \) \
 | xargs -0 ls -s | /usr/bin/sort -nr

