#!/bin/sh

# NOTE:
#  grepsr[c] -- uses xargs, much faster on Windows, but may hit
#                cmdline limit?
#  grepsrr[c] -- uses find -exec, much slower on Windows.

if [ -z "$*" ]
then echo Argument needed
     exit 1
fi

/usr/bin/find . \( \( -name .svn -o -name .git \) -prune -fprint /dev/null \) \
   -or \( -regex '.*\.\([cChH]\([cChH]\|[pPxX][pPxX]\)?\|stk\|l\|y\)' \
          -print0 \) \
 | xargs -0 grep "$@" /dev/null \
 | sed -e 's/^[^:]*:/[35m&[0m/'


