#!/bin/sh

if [ -n "$1" -a ! -e "$1" ]
then STATUSES=$1
     shift
else STATUSES=ACM
fi

do_exec () {
  exec vi -o `hg status "$@" | grep -e "^[${STATUSES}]" \
                             | cut -c2- \
                             | /usr/bin/sort`
}

if [ -n "$*" ]
then do_exec "$@"
else do_exec .
fi
