#!/bin/sh

SCRDIR=`dirname "$0"`

if [ -d /home/suan/exif-github ]
then export PYTHONPATH=/home/suan/exif-github:/home/suan/iptcinfo3
     python3 "${SCRDIR}/ipad.py" "$@"
     exit $?
fi

PYFILE=`cygpath -am "${SCRDIR}/ipad.py"`
PYTHON=/cygdrive/c/Python27/python.exe

ARGS=
for ARG in "$@"
do case ${ARG} in
      -*) ARGS="${ARGS} ${ARG}" ;;
      */*) ARGS="${ARGS} `cygpath -m "${ARG}"`" ;;
      *\\*) ARGS="${ARGS} `cygpath -m "${ARG}"`" ;;
      *) ARGS="${ARGS} ${ARG}" ;;
   esac
done

set -x
"${PYTHON}" "${PYFILE}" ${ARGS}
