#!/bin/bash

if [ "$1" != "filter" ]
then # Raw stage: fetch the data, feed to filtered stage

     GETTER="wget -q -O -"
     #GETTER="lynx -source"

     NUM_HRS=12

     case "$1" in
       6)  NUM_HRS=6 ;;
       12) NUM_HRS=12 ;;
       24) NUM_HRS=24 ;;
       36) NUM_HRS=36 ;;
     esac

     METARS_URL='http://adds.aviationweather.noaa.gov/metars/index.php?station_ids=KPEO&std_trans=standard&chk_metars=on&hoursStr=past+'${NUM_HRS}'+hours'

     ${GETTER} ${METARS_URL} | fgrep '<FONT' | sed -e 's/^.*\<\([0-9][0-9]\)\([0-9][0-9]\)\([0-9][0-9]\)Z\>.*\<\([0-9V][0-9R][0-9B]\)\([0-9][0-9]\)\(G[0-9][0-9]\)*KT\>.*\(\<M\?[0-9][0-9]\)\/.*$/\1 \2 \3 \4 \5\6 \7/' | $0 filter

else # Filter stage: convert from UTC, annotate directions, colorize
     while read day hr_utc min dir wind temp
     do
        HR_LOCAL=`date -d "${hr_utc}:00:00 UTC" +%H`
        if [ "${dir}" = VRB -o "${dir}" = 000 ]
        then DIR="   "
        else WINDDIR_QTR=`echo ${dir} / 22.5 | bc -l`
             case `printf %.0f ${WINDDIR_QTR}` in
               0) DIR="N  " ;;
               1) DIR="NNE" ;;
               2) DIR="NE " ;;
               3) DIR="ENE" ;;
               4) DIR="E  " ;;
               5) DIR="ESE" ;;
               6) DIR="SE " ;;
               7) DIR="SSE" ;;
               8) DIR="S  " ;;
               9) DIR="SSW" ;;
              10) DIR="SW " ;;
              11) DIR="WSW" ;;
              12) DIR="W  " ;;
              13) DIR="WNW" ;;
              14) DIR="NW " ;;
              15) DIR="NNW" ;;
              16) DIR="N  " ;;
             esac
        fi

        echo "${day}-[36m${HR_LOCAL}:${min}[0m [36m${dir}(${DIR})[0m-[33m${wind}[0mkt ${temp}'C"
     done
fi

