#!/bin/sh

SCRDIR=`dirname "$0"`

PYFILE=`cygpath -am "${SCRDIR}/long_exposure_from_video.py"`
PYTHON=python3

ARGS=
for ARG in "$@"
do case ${ARG} in
      -*) ARGS="${ARGS} ${ARG}" ;;
      */*) ARGS="${ARGS} `cygpath -m "${ARG}"`" ;;
      *\\*) ARGS="${ARGS} `cygpath -m "${ARG}"`" ;;
      *) ARGS="${ARGS} ${ARG}" ;;
   esac
done

set -x
"${PYTHON}" "${PYFILE}" ${ARGS}
