#!/bin/sh

SCRDIR=`dirname "$0"`

#PYFILE=`cygpath -am "${SCRDIR}/thermapp-video-adjust-cv.py"`
PYFILE=`cygpath -am "${SCRDIR}/thermapp-video-adjust-av.py"`
PYTHON=python3

ARGS=
for ARG in "$@"
do case ${ARG} in
      -*) ARGS="${ARGS} ${ARG}" ;;
      */*) ARGS="${ARGS} `cygpath -m "${ARG}"`" ;;
      *\\*) ARGS="${ARGS} `cygpath -m "${ARG}"`" ;;
      *) ARGS="${ARGS} ${ARG}" ;;
   esac
done

set -x
"${PYTHON}" "${PYFILE}" ${ARGS}
